CREATE TABLE BANK_ACCOUNTS (
  ACCOUNTID INT(11) PRIMARY KEY AUTO_INCREMENT,
  USERID INT(11) NOT NULL,
  ACCOUNTTYPE VARCHAR(50) NOT NULL,
  INITIALDEPOSIT DECIMAL(10, 2) NOT NULL,
  PHONENUMBER VARCHAR(15) NOT NULL,
  ADDRESS TEXT NOT NULL,
  FULLNAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  PROFILEPICTURE VARCHAR(255) DEFAULT NULL,
  DATEOFBIRTH DATE NOT NULL,
  GENDER VARCHAR(10) NOT NULL,
  CREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 
  -- New Fields
  PASSWORD VARCHAR(255) NOT NULL,
  ACCOUNTSTATUS ENUM('active', 'suspended', 'deleted') DEFAULT 'active',
  SECURITYQUESTION VARCHAR(255) DEFAULT NULL,
  SECURITYANSWER VARCHAR(255) DEFAULT NULL,
  TWOFA_ENABLED BOOLEAN DEFAULT FALSE,
  TWOFA_SECRET VARCHAR(255) DEFAULT NULL
);

-- Indexes
CREATE INDEX IDX_EMAIL ON USER_ACCOUNTS(EMAIL);

CREATE INDEX IDX_PHONENUMBER ON USER_ACCOUNTS(PHONENUMBER);