CREATE TABLE TRANSACTIONS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  USERID INT NOT NULL,
  TYPE ENUM('credit', 'debit') NOT NULL,
  AMOUNT DECIMAL(10, 2) NOT NULL,
  DESCRIPTION VARCHAR(255),
  CREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (USERID) REFERENCES USERSIGNUP(USERID)
);